/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import Form.Dashboard;
import java.awt.Color;
import Koneksi.Koneksi;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.SwingUtilities;

/**
 *
 * @author FARHAN
 */
public class TambahPengaduan extends javax.swing.JPanel {

    private byte[] fotoByteArray;
    private int nik = 0;
    private int idpetugas = 0;
    private int level;
    private PanelHome home;

    /**
     * Creates new form Form_1
     */
    public TambahPengaduan(int level, int nik, int idpetugas) {
        initComponents();
        this.nik = nik;
        this.level = level;
        this.idpetugas = idpetugas;
        Calendar calendar = Calendar.getInstance();
        Date today = calendar.getTime();

// Mengatur nilai TGL_PENGADUAN dengan tanggal hari ini
        TGL_PENGADUAN.setDate(today);
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);

        // Mengganti query SQL untuk mendapatkan nama masyarakat
        try {
            Connection kon = Koneksi.KoneksiDb();
            String query = "SELECT tbl_pengaduan.id_pengaduan, tbl_pengaduan.tgl_pengaduan, tbl_masyarakat.nama, tbl_pengaduan.isi_laporan, tbl_pengaduan.status FROM tbl_pengaduan INNER JOIN tbl_masyarakat ON tbl_pengaduan.nik = tbl_masyarakat.nik WHERE tbl_pengaduan.nik = ?";
            try ( PreparedStatement pstmt = kon.prepareStatement(query)) {
                pstmt.setInt(1, nik);
                try ( ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        String namaMasyarakat = rs.getString("nama");
                        TXT_NIK.setText("MYRK               :   " + namaMasyarakat);
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

        TXT_PATHFOTO.setEditable(false);

        BTN_CANCEL.addActionListener(e -> {
            PanelHome form1 = new PanelHome(level, nik, idpetugas);
            Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);

            if (dashboard != null) {
                dashboard.setForm(form1);
            }
        });
    }

    public void setFotoFromFileChooser() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("'.IMAGE", "jpg", "gif", "png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            TXT_PATHFOTO.setText(path);

            try {
                // blob => ImageIcon
                byte[] img = Files.readAllBytes(selectedFile.toPath());
                ImageIcon imageIcon = new ImageIcon(img);
                fotoByteArray = Files.readAllBytes(selectedFile.toPath());

                // UKURAN YANG AKAN DI TAMPILKAN
                int labelWidth = 320;
                int labelHeight = 320;

                // UKURAN GAMBAR ASLI
                int imageWidth = imageIcon.getIconWidth();
                int imageHeight = imageIcon.getIconHeight();

                // HITUNG SKALA UNTUK GAMBAR YANG BARU
                double scaleX = (double) labelWidth / (double) imageWidth;
                double scaleY = (double) labelHeight / (double) imageHeight;
                double scale = Math.min(scaleX, scaleY);

                //UBAH UKURAN GAMBAR DENGAN SKALA YANG SUDAH DI HITUNG
                Image scaledImage = imageIcon.getImage().getScaledInstance((int) (scale + imageWidth), (int) (scale + imageHeight), Image.SCALE_SMOOTH);

                // MENAMPILKAN GAMBAR KE LABEL
                lb_gambar.setIcon(new ImageIcon(new ImageIcon(scaledImage).getImage().getScaledInstance(320, 320, Image.SCALE_SMOOTH)));

            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new Panel.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TGL_PENGADUAN = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        TXT_NIK = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        TXT_LAPORAN = new javax.swing.JTextArea();
        BTN_CANCEL = new javax.swing.JButton();
        BTN_TAMBAH = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TXT_PATHFOTO = new javax.swing.JTextField();
        BTN_FOTO = new javax.swing.JButton();
        lb_gambar = new javax.swing.JLabel();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Tambah Pengaduan");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 350));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel7.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel2.setText("Tanggal Pengaduan");
        jPanel7.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        TGL_PENGADUAN.setBackground(new java.awt.Color(255, 255, 255));
        TGL_PENGADUAN.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel7.add(TGL_PENGADUAN, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 50));

        TXT_NIK.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TXT_NIK.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TXT_NIK, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(TXT_NIK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(250, 110));
        jPanel8.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel4.setText("Isi Laporan");
        jPanel8.add(jLabel4, java.awt.BorderLayout.CENTER);

        spTable.setPreferredSize(new java.awt.Dimension(234, 80));

        TXT_LAPORAN.setColumns(20);
        TXT_LAPORAN.setRows(5);
        spTable.setViewportView(TXT_LAPORAN);

        jPanel8.add(spTable, java.awt.BorderLayout.PAGE_END);

        BTN_CANCEL.setText("Kembali");
        BTN_CANCEL.setPreferredSize(new java.awt.Dimension(120, 30));
        BTN_CANCEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CANCELActionPerformed(evt);
            }
        });

        BTN_TAMBAH.setText("Tambah");
        BTN_TAMBAH.setPreferredSize(new java.awt.Dimension(120, 30));
        BTN_TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_TAMBAHActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(275, 50));
        jPanel9.setLayout(new java.awt.BorderLayout(0, 10));

        jLabel5.setText("Foto");
        jPanel9.add(jLabel5, java.awt.BorderLayout.CENTER);

        TXT_PATHFOTO.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel9.add(TXT_PATHFOTO, java.awt.BorderLayout.PAGE_END);

        BTN_FOTO.setText("Tambah Foto");
        BTN_FOTO.setPreferredSize(new java.awt.Dimension(120, 20));
        BTN_FOTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_FOTOActionPerformed(evt);
            }
        });
        jPanel9.add(BTN_FOTO, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(BTN_CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(BTN_TAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_CANCEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_TAMBAH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        lb_gambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(lb_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lb_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_TAMBAHActionPerformed
        Connection kon = Koneksi.KoneksiDb();
        String tglPengaduan = getFormattedCurrentDate(); // Mengasumsikan Anda memiliki metode untuk mendapatkan tanggal saat ini yang diformat
        String isiLaporan = TXT_LAPORAN.getText(); // Mengasumsikan Anda memiliki kolom teks untuk isi_laporan

        // Tambahkan kolom 'nik' ke query dan gunakan "RETURN_GENERATED_KEYS"
        String sql = "INSERT INTO tbl_pengaduan (id_pengaduan, nik, tgl_pengaduan, isi_laporan, foto, status) VALUES (DEFAULT, ?, ?, ?, ?, '0')";

        try ( PreparedStatement ps = kon.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, nik); // Mengasumsikan Anda memiliki nilai 'nik' yang tersedia
            ps.setString(2, tglPengaduan);
            ps.setString(3, isiLaporan);
            ps.setBytes(4, fotoByteArray);

            int result = ps.executeUpdate();

            if (result > 0) {
                // Dapatkan nilai auto-increment yang dihasilkan
                try ( ResultSet generatedKeys = ps.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        int generatedIdPengaduan = generatedKeys.getInt(1);
                        JOptionPane.showMessageDialog(null, "Pengaduan berhasil disimpan dengan ID: " + generatedIdPengaduan);
                        // Lakukan hal-hal lain setelah penyimpanan sukses
                        PanelHome form1 = new PanelHome(level, nik, idpetugas);
                        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);

                        if (dashboard != null) {
                            dashboard.setForm(form1);
                        }
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pengaduan gagal disimpan. Silakan coba lagi.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_BTN_TAMBAHActionPerformed

    private void BTN_CANCELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CANCELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_CANCELActionPerformed

    private void BTN_FOTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_FOTOActionPerformed
        setFotoFromFileChooser();
    }//GEN-LAST:event_BTN_FOTOActionPerformed

    public static String getFormattedCurrentDate() {
        // Mengatur format tanggal yang diinginkan
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        // Mendapatkan tanggal saat ini
        Date currentDate = new Date();

        // Mengonversi tanggal ke string dengan format yang diinginkan
        String formattedDate = dateFormat.format(currentDate);

        return formattedDate;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_CANCEL;
    private javax.swing.JButton BTN_FOTO;
    private javax.swing.JButton BTN_TAMBAH;
    private com.toedter.calendar.JDateChooser TGL_PENGADUAN;
    private javax.swing.JTextArea TXT_LAPORAN;
    private javax.swing.JLabel TXT_NIK;
    private javax.swing.JTextField TXT_PATHFOTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lb_gambar;
    private Panel.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    // End of variables declaration//GEN-END:variables
}
