/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Event.EventMenuSelected;
import Koneksi.Koneksi;
import Panel.TambahPengaduan;
import Panel.PanelHome;
import Form.Login;
import Panel.InfoAkun;
import Panel.TabelTanggapan;
import java.awt.Color;
import java.util.prefs.Preferences;
import javax.swing.JComponent;
import javax.swing.JPanel;

/**
 *
 * @author RAVEN
 */
public class Dashboard extends javax.swing.JFrame {

    public Preferences preferences = Preferences.userNodeForPackage(Login.class);
    /**
     * Creates new form Main
     */
    private PanelHome TABLEPENGADUAN;
    private TabelTanggapan TABLETANGGAPAN;
    
    
    private InfoAkun INFOAKUN;

    private int level;
    private int nik = 0;
    private int idpetugas;

    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    public Connection kon = Koneksi.KoneksiDb();

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public Dashboard(int level, int nik, int idpetugas) {
        this.level = level;
        this.nik = nik;
        this.idpetugas = idpetugas;

        initComponents(); // Inisialisasi komponen-komponen form dashboard
        //judul()
        // Lakukan tindakan sesuai dengan level di sini
        if (level == 1) {
            //jButton1.setEnabled(false);
            // Tindakan yang sesuai untuk petugas
        } else if (level == 2) {
            // Tindakan yang sesuai untuk administrator
        } else if (level == 3) {
//            jButton1.setEnabled(false);
            //jButton2.setEnabled(false);
            // Tindakan yang sesuai untuk level ketiga
        }

        setBackground(new Color(0, 0, 0, 0));
        TABLEPENGADUAN = new PanelHome(level, nik, idpetugas);
        TABLETANGGAPAN = new TabelTanggapan(level, nik, idpetugas);
        INFOAKUN = new InfoAkun(level, nik, idpetugas);
        menu.initMoving(Dashboard.this);
        menu.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                if (level == 3) {
                    if (level == 3 && !(index == 2 || index == 7 || index == 8)) {
                        JOptionPane.showMessageDialog(Dashboard.this, "Hanya Dapat Diakses Oleh Petugas & Administrator");
                        return; // Hentikan eksekusi lebih lanjut
                    }
                }

                if (index == 2) {
                    setForm(TABLEPENGADUAN);
                } else if (index == 3) {
                    setForm(TABLETANGGAPAN);
                } else if (index == 7) {
                    setForm(INFOAKUN);
                } else if (index == 8) {
                    // Saat logout
                    String rememberedUsername = preferences.get("rememberedUsername", "");
                    if (!rememberedUsername.isEmpty()) {
                        // Set nilai TXT_USERNAME dari objek Login
                        Login DHB1 = new Login();
                        DHB1.setUsername(rememberedUsername);

                        // Tampilkan form login
                        DHB1.setVisible(true);
                        setVisible(false);
                    } else {
                        // Tampilkan form login
                        Login DHB1 = new Login();
                        DHB1.setVisible(true);
                        setVisible(false);
                    }

                }

            }
        });
    }

    public void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new Panel.PanelBorder();
        menu = new Panel.PanelMenu();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(1, 0, 1).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private Panel.PanelMenu menu;
    private Panel.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
