/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

/**
 *
 * @author FARHAN
 */
import Form.Dashboard;
import Koneksi.Koneksi;
import Panel.PanelHome;
import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.prefs.Preferences;

public class Login extends javax.swing.JFrame {

    public Preferences preferences = Preferences.userNodeForPackage(Login.class);

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        // Menambahkan event listener ke JLabel
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

    }

    public void setUsername(String username) {
        TXT_USERNAME.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXT_USERNAME = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TXT_PASSWORD = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        CB_INGATSAYA = new javax.swing.JCheckBox();
        LB_LUPAPASSWORD = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        BTN_LOGIN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 450));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 430));

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Selamat Datang");
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 150));

        jPanel6.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel6.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel2.setText("Username");
        jPanel6.add(jLabel2, java.awt.BorderLayout.CENTER);

        TXT_USERNAME.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel6.add(TXT_USERNAME, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel7.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel3.setText("Password");
        jPanel7.add(jLabel3, java.awt.BorderLayout.CENTER);

        TXT_PASSWORD.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel7.add(TXT_PASSWORD, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel8.setLayout(new java.awt.BorderLayout());

        CB_INGATSAYA.setText("Ingat Saya");
        CB_INGATSAYA.setPreferredSize(new java.awt.Dimension(85, 25));
        CB_INGATSAYA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_INGATSAYAActionPerformed(evt);
            }
        });
        jPanel8.add(CB_INGATSAYA, java.awt.BorderLayout.WEST);

        LB_LUPAPASSWORD.setText("Lupa Password ?");
        LB_LUPAPASSWORD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LB_LUPAPASSWORDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LB_LUPAPASSWORDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LB_LUPAPASSWORDMouseExited(evt);
            }
        });
        jPanel8.add(LB_LUPAPASSWORD, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel8);

        jPanel1.add(jPanel5);

        jPanel9.setPreferredSize(new java.awt.Dimension(400, 50));

        BTN_LOGIN.setText("Login");
        BTN_LOGIN.setPreferredSize(new java.awt.Dimension(250, 30));
        BTN_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LOGINActionPerformed(evt);
            }
        });
        jPanel9.add(BTN_LOGIN);

        jPanel1.add(jPanel9);

        jLabel5.setText("Tidak Punya Akun ? Mendaftar Segera");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 430));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 29));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/5481497_2769504-removebg-preview (1) (1).png"))); // NOI18N
        jPanel2.add(jLabel6);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LOGINActionPerformed
        // TODO add your handling code here:
        Connection kon = Koneksi.KoneksiDb();
        int level = 0;
        int nik = 0;
        int idpetugas = 0;
        try {
            Statement st = kon.createStatement();
            String sql = "SELECT * FROM tbl_petugas where username ='" + TXT_USERNAME.getText() + "' and password = '" + TXT_PASSWORD.getText() + "'";
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                if (CB_INGATSAYA.isSelected()) {
                    String rememberedUsername = TXT_USERNAME.getText();
                    preferences.put("rememberedUsername", rememberedUsername);
//                    System.out.println("Username remembered: " + rememberedUsername);
                } else {
                    preferences.remove("rememberedUsername");
                }

                if (rs.getString("level").equals("petugas")) {
                    int idPetugasFromResultSet = rs.getInt("id_petugas");
                    

                    Dashboard FRD1 = new Dashboard(1, 0, idPetugasFromResultSet);
                    FRD1.setVisible(true);
                    this.dispose();
                } else if (rs.getString("level").equals("administrator")) {
                    int idPetugasFromResultSet = rs.getInt("id_petugas");
                    

                    Dashboard FRD2 = new Dashboard(2, 0, idPetugasFromResultSet);
                    FRD2.setVisible(true);
                    this.dispose();
                }
            } else {
                Statement st2 = kon.createStatement();
                String sql2 = "SELECT * FROM tbl_masyarakat where username ='" + TXT_USERNAME.getText() + "' and password = '" + TXT_PASSWORD.getText() + "'";
                ResultSet rs2 = st2.executeQuery(sql2);

                if (rs2.next()) {
                    if (CB_INGATSAYA.isSelected()) {
                        String rememberedUsername = TXT_USERNAME.getText();
                        preferences.put("rememberedUsername", rememberedUsername);
                        //System.out.println("Username remembered: " + rememberedUsername);
                    } else {
                        preferences.remove("rememberedUsername");
                    }
                    Dashboard FRD3 = new Dashboard(3, rs2.getInt("nik"), 0);

                    FRD3.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Maaf password atau username akun anda salah");
                    TXT_USERNAME.setText("");
                    TXT_PASSWORD.setText("");
                    TXT_USERNAME.requestFocus();
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_BTN_LOGINActionPerformed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(new Color(0x00A9FF));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Register Reg = new Register();
//                  FRD1.setContentPane(new PanelHome(1)); // Pass the level to PanelHome
        Reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void LB_LUPAPASSWORDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_LUPAPASSWORDMouseEntered
        LB_LUPAPASSWORD.setForeground(new Color(0xFFEA20));
    }//GEN-LAST:event_LB_LUPAPASSWORDMouseEntered

    private void LB_LUPAPASSWORDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_LUPAPASSWORDMouseExited
        LB_LUPAPASSWORD.setForeground(Color.BLACK);
    }//GEN-LAST:event_LB_LUPAPASSWORDMouseExited

    private void LB_LUPAPASSWORDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LB_LUPAPASSWORDMouseClicked
        Connection kon = Koneksi.KoneksiDb();
        String input = JOptionPane.showInputDialog("Masukkan nomor telepon:");

// Lakukan pengecekan di database
// Misalnya, ganti dengan SQL query yang sesuai untuk mencari data pengguna berdasarkan nomor telepon
        String sql = "SELECT * FROM tbl_masyarakat WHERE no_telepon = ?";
        try ( PreparedStatement ps = kon.prepareStatement(sql)) {
            ps.setString(1, input);

            try ( ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    // Pengguna ditemukan, tampilkan profil
                    String profil = "Nama: " + rs.getString("nama") + "\n"
                            + "Username: " + rs.getString("username") + "\n"
                            + "Password: " + rs.getString("password") + "\n"
                            + "No. Telepon: " + rs.getString("no_telepon");

                    // Tampilkan profil menggunakan JOptionPane
                    JOptionPane.showMessageDialog(null, profil, "Profil Pengguna", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Pengguna tidak ditemukan.");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_LB_LUPAPASSWORDMouseClicked

    private void CB_INGATSAYAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_INGATSAYAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_INGATSAYAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_LOGIN;
    private javax.swing.JCheckBox CB_INGATSAYA;
    private javax.swing.JLabel LB_LUPAPASSWORD;
    private javax.swing.JPasswordField TXT_PASSWORD;
    private javax.swing.JTextField TXT_USERNAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
