/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import Koneksi.Koneksi;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author FARHAN
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        TXT_NOTELEPON.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_NOTELEPONKeyTyped(evt);
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TXT_NAMA = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXT_USERNAME = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TXT_PASSWORD = new javax.swing.JPasswordField();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TXT_NOTELEPON = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        CB_INGATSAYA = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        BTN_REGISTER = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 430));

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Register");
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 250));

        jPanel11.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel11.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel4.setText("Nama");
        jPanel11.add(jLabel4, java.awt.BorderLayout.CENTER);

        TXT_NAMA.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel11.add(TXT_NAMA, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel11);

        jPanel6.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel6.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel2.setText("Username");
        jPanel6.add(jLabel2, java.awt.BorderLayout.CENTER);

        TXT_USERNAME.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel6.add(TXT_USERNAME, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel7.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel3.setText("Password");
        jPanel7.add(jLabel3, java.awt.BorderLayout.CENTER);

        TXT_PASSWORD.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel7.add(TXT_PASSWORD, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel7);

        jPanel10.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel10.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel6.setText("No Telepon");
        jPanel10.add(jLabel6, java.awt.BorderLayout.CENTER);

        TXT_NOTELEPON.setPreferredSize(new java.awt.Dimension(70, 30));
        TXT_NOTELEPON.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_NOTELEPONKeyTyped(evt);
            }
        });
        jPanel10.add(TXT_NOTELEPON, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel10);

        jPanel8.setPreferredSize(new java.awt.Dimension(250, 20));
        jPanel8.setLayout(new java.awt.BorderLayout());

        CB_INGATSAYA.setText("Ingat Saya");
        CB_INGATSAYA.setPreferredSize(new java.awt.Dimension(85, 25));
        jPanel8.add(CB_INGATSAYA, java.awt.BorderLayout.WEST);

        jPanel5.add(jPanel8);

        jPanel1.add(jPanel5);

        jPanel9.setPreferredSize(new java.awt.Dimension(400, 50));

        BTN_REGISTER.setText("Register");
        BTN_REGISTER.setPreferredSize(new java.awt.Dimension(250, 30));
        BTN_REGISTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTERActionPerformed(evt);
            }
        });
        jPanel9.add(BTN_REGISTER);

        jPanel1.add(jPanel9);

        jLabel5.setText("Sudah Punya Akun ? Login Segera");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 430));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 29));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/rsz_12463952_4966434.jpg"))); // NOI18N
        jPanel2.add(jLabel7);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_REGISTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTERActionPerformed
        // TODO add your handling code here:
        Connection kon = Koneksi.KoneksiDb();
        int level = 0;
        String nama = TXT_NAMA.getText();
        String username = TXT_USERNAME.getText();
        String password = String.valueOf(TXT_PASSWORD.getPassword());
        String notelepon = TXT_NOTELEPON.getText();

        if (validateFields(nama, username, password, notelepon)) {
            try {
                // Tambahkan kolom 'nik' ke query dan gunakan "RETURN_GENERATED_KEYS"
                String sql = "INSERT INTO tbl_masyarakat (nik, nama, username, password, no_telepon) VALUES (DEFAULT, ?, ?, ?, ?)";
                try ( PreparedStatement ps = kon.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS)) {
                    ps.setString(1, nama);
                    ps.setString(2, username);
                    ps.setString(3, password);
                    ps.setString(4, notelepon);

                    int result = ps.executeUpdate();

                    if (result > 0) {
                        // Dapatkan nilai auto-increment yang dihasilkan
                        try ( ResultSet generatedKeys = ps.getGeneratedKeys()) {
                            if (generatedKeys.next()) {
                                int generatedNIK = generatedKeys.getInt(1);
                                String registeredName = nama;
                                String registeredUsername = username;
                                JOptionPane.showMessageDialog(null, "Pendaftaran berhasil Atas Nama : " + registeredName + ". Silakan login.");
                                reset();
                                Login Lgn = new Login();
                                if (CB_INGATSAYA.isSelected()) {
                                    Lgn.setUsername(registeredUsername);
                                }
                                
                                Lgn.setVisible(true);
                                this.dispose();
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Pendaftaran gagal. Silakan coba lagi.");
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

//        try {
//            Statement st = kon.createStatement();
//            String sql = "SELECT * FROM tbl_petugas where username ='" + TXT_USERNAME.getText() + "' and password = '" + TXT_PASSWORD.getText() + "'";
//            ResultSet rs = st.executeQuery(sql);
//
//            if (rs.next()) {
//                if (rs.getString("level").equals("petugas")) {
//                    Dashboard FRD1 = new Dashboard(1);
//                    //                  FRD1.setContentPane(new PanelHome(1)); // Pass the level to PanelHome
//                    FRD1.setVisible(true);
//                    this.dispose();
//                } else if (rs.getString("level").equals("administrator")) {
//                    Dashboard FRD2 = new Dashboard(2);
//                    //FRD2.setContentPane(new PanelHome(2)); // Pass the level to PanelHome
//                    FRD2.setVisible(true);
//                    this.dispose();
//                }
//            } else {
//                Statement st2 = kon.createStatement();
//                String sql2 = "SELECT * FROM tbl_masyarakat where username ='" + TXT_USERNAME.getText() + "' and password = '" + TXT_PASSWORD.getText() + "'";
//                ResultSet rs2 = st2.executeQuery(sql2);
//
//                if (rs2.next()) {
//                    Dashboard FRD3 = new Dashboard(3);
//                    //    FRD3.setContentPane(new PanelHome(3)); // Pass the level to PanelHome
//                    FRD3.setVisible(true);
//                    this.dispose();
//                } else {
//                    JOptionPane.showMessageDialog(null, "Maaf password atau username akun anda salah");
//                    TXT_USERNAME.setText("");
//                    TXT_PASSWORD.setText("");
//                    TXT_USERNAME.requestFocus();
//                }
//            }
//
////        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_BTN_REGISTERActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Login Lgn = new Login();
        Lgn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(new Color(0x00A9FF));

    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel5MouseExited

    private void TXT_NOTELEPONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_NOTELEPONKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume(); // Mencegah karakter yang tidak valid dimasukkan
        }
    }//GEN-LAST:event_TXT_NOTELEPONKeyTyped

    private boolean validateFields(String nama, String username, String password, String notelepon) {
        if (nama.isEmpty() || username.isEmpty() || password.isEmpty() || notelepon.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mohon isi semua kolom");
            return false;
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    public void reset() {
        TXT_NAMA.setText("");
        TXT_USERNAME.setText("");
        TXT_PASSWORD.setText("");
        TXT_NOTELEPON.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_REGISTER;
    private javax.swing.JCheckBox CB_INGATSAYA;
    private javax.swing.JTextField TXT_NAMA;
    private javax.swing.JTextField TXT_NOTELEPON;
    private javax.swing.JPasswordField TXT_PASSWORD;
    private javax.swing.JTextField TXT_USERNAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
